import Head from "next/head";

import { TokensContainer, QueryProvider } from "@components/layout";

import styles from "../styles/app.module.scss";

export default function Home() {
  return (
    <QueryProvider>
      <div>
        <Head>
          <title>Supa-Hiro</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.app}>
          <header className={styles.app__header}>
            <h1 className={styles.app__title}>Welcome to Supa-Hiro</h1>
          </header>

          <TokensContainer />
        </main>
      </div>
    </QueryProvider>
  );
}
